spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cristaldoplf/back-final-microservice
          default-label: main

server:
  port: 8888
